version: '3'
services:
  database:
    build: ./database
    ports:
      - "3306:3306"
    platform: linux/x86_64
  backend:
    build: ./
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment: 
      - DBHOST=database